apiVersion: apps/v1
kind: Deployment
metadata:
  name: usercontext
  labels:
    app: usercontext
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usercontext
  template:
    metadata:
      labels:
        app: usercontext
    spec:
      containers:
        - name: usercontext
          image: "username/usercontext:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
