<template>
    <div>
        <Number
            label="DeathReportId"
            v-model="value.deathReportId"
            :editMode="editMode"
        />
        <Number
            label="FuneralInfoId"
            v-model="value.funeralInfoId"
            :editMode="editMode"
        />
        <Number
            label="DeathReportTemplateId"
            v-model="value.deathReportTemplateId"
            :editMode="editMode"
        />
        <String
            label="DeathReportFilePath"
            v-model="value.deathReportFilePath"
            :editMode="editMode"
        />
        <String
            label="DeathReportFileUrl"
            v-model="value.deathReportFileUrl"
            :editMode="editMode"
        />
        <String
            label="DeathReportStatus"
            v-model="value.deathReportStatus"
            :editMode="editMode"
        />
        <Date
            label="DeathReportCreatedAt"
            v-model="value.deathReportCreatedAt"
            :editMode="editMode"
        />
        <Number
            label="CustomerId"
            v-model="value.customerId"
            :editMode="editMode"
        />
        <String
            label="CustomerName"
            v-model="value.customerName"
            :editMode="editMode"
        />
        <String
            label="CustomerRrn"
            v-model="value.customerRrn"
            :editMode="editMode"
        />
        <String
            label="CustomerPhone"
            v-model="value.customerPhone"
            :editMode="editMode"
        />
        <String
            label="DeceasedName"
            v-model="value.deceasedName"
            :editMode="editMode"
        />
        <Number
            label="DeceasedAge"
            v-model="value.deceasedAge"
            :editMode="editMode"
        />
        <Date
            label="DeceasedDate"
            v-model="value.deceasedDate"
            :editMode="editMode"
        />
        <Date
            label="DeceasedBirthOfDate"
            v-model="value.deceasedBirthOfDate"
            :editMode="editMode"
        />
        <String
            label="DeceasedGender"
            v-model="value.deceasedGender"
            :editMode="editMode"
        />
        <String
            label="DeceasedNameHanja"
            v-model="value.deceasedNameHanja"
            :editMode="editMode"
        />
        <String
            label="DeceasedRrn"
            v-model="value.deceasedRrn"
            :editMode="editMode"
        />
        <String
            label="DeceasedReligion"
            v-model="value.deceasedReligion"
            :editMode="editMode"
        />
        <String
            label="DeceasedRelationToHouseholdHead"
            v-model="value.deceasedRelationToHouseholdHead"
            :editMode="editMode"
        />
        <Date
            label="ReportRegistrationDate"
            v-model="value.reportRegistrationDate"
            :editMode="editMode"
        />
        <String
            label="ReporterName"
            v-model="value.reporterName"
            :editMode="editMode"
        />
        <String
            label="ReporterRrn"
            v-model="value.reporterRrn"
            :editMode="editMode"
        />
        <String
            label="ReporterRelationToDeceased"
            v-model="value.reporterRelationToDeceased"
            :editMode="editMode"
        />
        <String
            label="ReporterAddress"
            v-model="value.reporterAddress"
            :editMode="editMode"
        />
        <String
            label="ReporterPhone"
            v-model="value.reporterPhone"
            :editMode="editMode"
        />
        <String
            label="ReporterEmail"
            v-model="value.reporterEmail"
            :editMode="editMode"
        />
        <String
            label="SubmitterName"
            v-model="value.submitterName"
            :editMode="editMode"
        />
        <String
            label="SubmitterRrn"
            v-model="value.submitterRrn"
            :editMode="editMode"
        />
        <String
            label="FuneralCompanyName"
            v-model="value.funeralCompanyName"
            :editMode="editMode"
        />
        <String
            label="DirectorName"
            v-model="value.directorName"
            :editMode="editMode"
        />
        <String
            label="DirectorPhone"
            v-model="value.directorPhone"
            :editMode="editMode"
        />
        <String
            label="FuneralHomeName"
            v-model="value.funeralHomeName"
            :editMode="editMode"
        />
        <String
            label="MortuaryInfo"
            v-model="value.mortuaryInfo"
            :editMode="editMode"
        />
        <String
            label="FuneralHomeAddress"
            v-model="value.funeralHomeAddress"
            :editMode="editMode"
        />
        <String
            label="FuneralDuration"
            v-model="value.funeralDuration"
            :editMode="editMode"
        />
        <String
            label="ProcessionDateTime"
            v-model="value.processionDateTime"
            :editMode="editMode"
        />
        <String
            label="BurialSiteInfo"
            v-model="value.burialSiteInfo"
            :editMode="editMode"
        />
        <String
            label="ChiefMourners"
            v-model="value.chiefMourners"
            :editMode="editMode"
        />
        <String
            label="TemplateKeyword"
            v-model="value.templateKeyword"
            :editMode="editMode"
        />
        <v-row class="ma-0 pa-0">
            <v-spacer></v-spacer>
            <v-btn width="64px" color="primary" @click="save">
                저장
            </v-btn>
        </v-row>
    </div>
</template>


<script>
import BaseEntity from './base-ui/BaseEntity.vue'

export default {
    name: 'DeathReport',
    mixins:[BaseEntity],
    components:{
    },
    
    data: () => ({
        path: "deathReports",
        value: {
        }
    }),
    created(){
    },
    computed:{
    },
    methods: {
    },
}
</script>
