apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataanalysis
  labels:
    app: dataanalysis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataanalysis
  template:
    metadata:
      labels:
        app: dataanalysis
    spec:
      containers:
        - name: dataanalysis
          image: "username/dataanalysis:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
