apiVersion: apps/v1
kind: Deployment
metadata:
  name: funeralcontext
  labels:
    app: funeralcontext
spec:
  replicas: 1
  selector:
    matchLabels:
      app: funeralcontext
  template:
    metadata:
      labels:
        app: funeralcontext
    spec:
      containers:
        - name: funeralcontext
          image: "username/funeralcontext:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
