apiVersion: apps/v1
kind: Deployment
metadata:
  name: funeralcontextai
  labels:
    app: funeralcontextai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: funeralcontextai
  template:
    metadata:
      labels:
        app: funeralcontextai
    spec:
      containers:
        - name: funeralcontextai
          image: "username/funeralcontextai:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
